name: Test
on: [push, pull_request]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-15
          - macos-15-intel
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
      with: { submodules: recursive }
    - uses: prefix-dev/setup-pixi@v0.9.4
      with: { pixi-version: v0.68.0 }
    - name: run standardese
      run: pixi run standardese include/standardese/logger.hpp
    - name: run tests
      run: pixi run test
